[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3001"

[healthcheck]
path = "/api/v1/health"
timeout = 30
interval = 60

[scaling]
minReplicas = 1
maxReplicas = 3

[networking]
serviceDomain = "smartalk-backend"

[build.env]
NODE_ENV = "production"

[variables]
# 这些变量需要在 Railway 控制台中设置
# DATABASE_URL = "postgresql://..."
# JWT_SECRET = "your-jwt-secret"
# JWT_REFRESH_SECRET = "your-refresh-secret"
# REDIS_URL = "redis://..."
# CORS_ORIGIN = "https://your-frontend-domain.vercel.app"
