apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartalk-backend
  namespace: smartalk
  labels:
    app: smartalk-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: smartalk-backend
  template:
    metadata:
      labels:
        app: smartalk-backend
    spec:
      containers:
      - name: backend
        image: smartalk/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: smartalk-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: smartalk-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: smartalk-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: smartalk-backend-service
  namespace: smartalk
spec:
  selector:
    app: smartalk-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP