# This is a template file - actual secrets should be created securely
apiVersion: v1
kind: Secret
metadata:
  name: smartalk-secrets
  namespace: smartalk
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  database-url: <BASE64_ENCODED_DATABASE_URL>
  redis-url: <BASE64_ENCODED_REDIS_URL>
  jwt-secret: <BASE64_ENCODED_JWT_SECRET>
  
---
# Example of how to create secrets:
# kubectl create secret generic smartalk-secrets \
#   --from-literal=database-url="postgresql://user:pass@host:5432/db" \
#   --from-literal=redis-url="redis://user:pass@host:6379" \
#   --from-literal=jwt-secret="your-super-secret-jwt-key" \
#   --namespace=smartalk